//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TekaTeknikMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacts
    {
        public int ContactId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string Relation { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
