//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TekaTeknikMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.Contacts = new HashSet<Contacts>();
            this.Payments = new HashSet<Payments>();
            this.Permissions = new HashSet<Permissions>();
        }
    
        public int EmployeeId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<int> AgiId { get; set; }
        public string FirstName { get; set; }
        public string Lastname { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PlaceOfBirth { get; set; }
        public string MobilePhone { get; set; }
        public string Mail { get; set; }
        public Nullable<int> Salary { get; set; }
        public string Address { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string EmployeeCode { get; set; }
        public string Nationality { get; set; }
        public string IdentyNumber { get; set; }
        public Nullable<System.DateTime> StartDay { get; set; }
        public Nullable<System.DateTime> EndDay { get; set; }
    
        public virtual Agis Agis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contacts> Contacts { get; set; }
        public virtual Departments Departments { get; set; }
        public virtual Districts Districts { get; set; }
        public virtual Tasks Tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payments> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permissions> Permissions { get; set; }
    }
}
