//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TekaTeknikMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int PaymentId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> AgiId { get; set; }
        public Nullable<int> Amount { get; set; }
        public string PaymentType { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Agis Agis { get; set; }
    }
}
