//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TekaTeknikMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permissions
    {
        public int PermissionId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> StartDay { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<System.DateTime> EndDay { get; set; }
        public string PermissionType { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
